From microsoft/dotnet:2.1-sdk as build

ARG BUILDCONFIG=RELEASE
ARG VERSION=1.0.0

COPY AnimalsPets.csproj /build/

RUN dotnet restore ./build/AnimalsPets.csproj

COPY . ./build/
WORKDIR /build/
RUN dotnet publish ./AnimalsPets.csproj -c  $BUILDCONFIG -o out /p:Version=$VERSION

FROM microsoft/dotnet:2.1-aspnetcore-runtime
WORKDIR /app

COPY --from=build /build/out .

ENTRYPOINT ["dotnet","AnimalsPets.dll"]